### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by tiagmoraismorgado** [OSAlt/geek-beacon-site#5]
hey nixie. i want to collaborate in your new project. hope you are doing fine.

**Comment by safaci2000** [comment]
Added a note on the contribution..though this particular site will probably have a revamp.  You're welcome to contribute.

**Comment by hollowdoor** [comment]
@safaci2000 What kind of revamp? Are you thinking the entire thing will be redone?

I was thinking of contributing some design ideas, but if you're going to redo the whole thing it might be pertinent for me to wait.

**Comment by safaci2000** [comment]
@hollowdoor Well, right now it's just HTML/CSS.  I want to get the final plan on what we're building and we'll probably do a radical make over.  But most likely we'll have a framework we're using.. both on the UI/JS side and backend a database etc.... 

Hence my comment to limit the work on here since much of it may go away.

**Comment by hollowdoor** [comment]
@safaci2000 Where do you suppose you'll be discussing plans? I'd be interested in helping if I can. Or is there a "benevolent dictator for life" that will be forming most of the plan?

**Comment by safaci2000** [comment]
I linked in the main README to a mailing list.  That's the only place you need to join if you want to get involved.

**Comment by hollowdoor** [comment]
Ok thanks. I just applied.
